upd(d_angel.zig)
The error: incompatible types: 'c_int' and 'void' on Line 81.
​In Zig, a defer statement must evaluate to void.
The angel_a C-function ma_decoder_uninit() returns a status code of type ma_result (which translates to c_int in Zig). Because I wrote defer if (has_vis) c.ma_decoder_uninit(&v_decoder);, the return type of that line became c_int. Zig immediately blocked the compilation because I didn't explicitly capture or discard the return value.